# Test we can logon to 'webservers' and execute python with json lib.
# ansible webservers -m ping

# Example from an Ansible Playbook
---
- hosts: all
  tasks:
    - name: test connection
      ping:

